import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import fs from 'node:fs/promises';
const origin = process.env.E2E_ORIGIN || 'http://127.0.0.1:3001';
const ownerPassword = process.env.E2E_OWNER_PASSWORD;
if (!ownerPassword) throw new Error('Set E2E_OWNER_PASSWORD for a disposable local database.');
const slug = `portal-${Date.now()}`;
const browser = await chromium.launch({ channel: process.env.E2E_BROWSER_CHANNEL || 'chrome', headless: true });
const context = await browser.newContext({ viewport:{width:1365,height:900} });
const page = await context.newPage();
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const login = async (path,id,password) => {
  await page.goto(origin+path);
  await page.getByLabel('Login ID',{exact:true}).fill(id);
  await page.getByLabel('Password',{exact:true}).fill(password);
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
};
const logout = async () => {
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.getByRole('button',{name:'Sign in',exact:true}).waitFor();
};
try {
  await login('/platform',process.env.E2E_OWNER_LOGIN || 'owner',ownerPassword);
  await page.getByRole('button',{name:'Add company'}).click();
  await page.getByLabel('Company name',{exact:true}).fill('Acme Test Dispatch');
  await page.getByLabel('Company identifier',{exact:true}).fill(slug);
  await page.getByLabel('Administrator login ID',{exact:true}).fill('acme-admin');
  const adminPassword = await page.getByLabel('Initial password',{exact:true}).inputValue();
  assert.ok(adminPassword.length>=20);
  await page.getByRole('button',{name:'Create company',exact:true}).click();
  await page.getByRole('heading',{name:'Login details ready'}).waitFor();
  assert.ok((await page.getByLabel('Login details',{exact:true}).inputValue()).includes(`/${slug}/dispatch`));
  await page.getByRole('button',{name:'Done',exact:true}).click();
  await logout();
  await login(`/${slug}/dispatch`,'acme-admin',adminPassword);
  await page.getByRole('button',{name:'Add customer'}).click();
  await page.getByLabel('Customer name',{exact:true}).fill('ABC Trading');
  await page.getByLabel('Customer number',{exact:true}).fill('CUST-001');
  await page.getByLabel('Login ID',{exact:true}).fill('abc-customer');
  const customerPassword = await page.getByLabel('Initial password',{exact:true}).inputValue();
  await page.getByRole('button',{name:'Create customer',exact:true}).click();
  await page.getByRole('heading',{name:'Login details ready'}).waitFor();
  await page.getByRole('button',{name:'Done',exact:true}).click();
  await logout();
  await login(`/${slug}/customer`,'abc-customer',customerPassword);
  await page.getByRole('heading',{name:'ABC Trading',exact:true}).waitFor();
  assert.equal(await page.getByLabel('Current password',{exact:true}).count(),0,'No forced first-login change');
  await page.getByLabel('Contact name',{exact:true}).fill('Jane Customer');
  await page.getByLabel('Contact email',{exact:true}).fill('jane@example.com');
  await page.getByLabel('Phone',{exact:true}).fill('+1 604 555 0123');
  await page.getByLabel('Address',{exact:true}).fill('123 Main Street, Vancouver, BC');
  await page.getByRole('button',{name:'Save profile',exact:true}).click();
  await page.getByText('Profile saved.',{exact:true}).waitFor();
  await page.reload();
  await page.getByRole('heading',{name:'ABC Trading',exact:true}).waitFor();
  assert.equal(await page.getByLabel('Contact name',{exact:true}).inputValue(),'Jane Customer');
  const output = process.env.E2E_SCREENSHOT_DIR;
  if (output) { await fs.mkdir(output,{recursive:true}); await page.screenshot({path:`${output}/customer-desktop.png`,fullPage:true}); }
  await page.getByRole('button',{name:'Account settings',exact:true}).click();
  await page.getByLabel('Current password',{exact:true}).fill(customerPassword);
  await page.getByLabel('New password',{exact:true}).fill('Customer-new-password-123!');
  await page.getByLabel('Confirm new password',{exact:true}).fill('Customer-new-password-123!');
  await page.getByRole('button',{name:'Change password',exact:true}).click();
  await page.getByText('Password changed.',{exact:true}).waitFor();
  const stored = await page.evaluate(()=>JSON.stringify({...localStorage}));
  assert.ok(!stored.includes(customerPassword) && !stored.includes('Customer-new-password-123!'));
  await logout();
  await login(`/${slug}/customer`,'abc-customer','Customer-new-password-123!');
  await page.getByRole('heading',{name:'ABC Trading',exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  if (output) await page.screenshot({path:`output/mobile.png`.replace('output',output),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No mobile horizontal overflow');
  await logout();
  await login(`/${slug}/dispatch`,'acme-admin',adminPassword);
  await page.getByText('Jane Customer · jane@example.com',{exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  console.log('PASS: company creation, customer creation, initial login without password gate, persistent profile, optional password change, dispatcher visibility and responsive layout.');
} finally { await browser.close(); }
